spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          timezone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres-0/candles
    url: jdbc:postgresql://127.0.0.1:5432/candles
    username: postgres
    password: postgres
