spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          timezone: UTC
        format_sql: true
  datasource:
    #    url: jdbc:postgresql://postgres-0/candles
    url: jdbc:postgresql://127.0.0.1:5432/candles
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:candles-init.sql