spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-0/candles
    username: postgres
    password: postgres
