spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          timezone: UTC
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
info:
  app:
    name: Candles
    description: AromaHouse management application
    version: 0.1
    author: Ruslan Kostiuk
springdoc:
  default-produces-media-type: application/json