CREATE TABLE component_types (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE components (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    type_id int NOT NULL,
    FOREIGN KEY (type_id) REFERENCES component_types(id)
);

CREATE TABLE component_receipts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_on date NOT NULL,
    total_price numeric(12, 2) NOT NULL,
    amount_received numeric(12, 3) NOT NULL,
    component_id bigint NOT NULL,
    FOREIGN KEY (component_id) REFERENCES components(id)
);

