CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    price numeric(12, 2) NOT NULL,
    quantity_in_stock int NOT NULL,
    CONSTRAINT not_empty_product_name CHECK(length(name) > 0),
    CONSTRAINT not_negative_product_quantity_in_stock CHECK(quantity_in_stock >= 0)
);

CREATE TABLE product_components (
    product_id bigint NOT NULL,
    component_id bigint NOT NULL,
    required_amount numeric(12, 3) NOT NULL,
    CONSTRAINT unique_product_component UNIQUE(product_id, component_id),
    constraint not_negative_product_component_required_amount CHECK(required_amount >= 0)
);

CREATE TABLE sales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sold_on date NOT NULL
);

CREATE TABLE product_sales (
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL,
    product_count int NOT NULL,
    product_price numeric(12, 2) NOT NULL,
    CONSTRAINT unique_product_sale UNIQUE(product_id, sale_id),
    CONSTRAINT positive_product_sale_count CHECK(product_count > 0),
    CONSTRAINT not_negative_product_sale_price CHECK(product_price >= 0)
);